Dubs Bad Hygiene
Kitsune912/Portuguese-Pack pull request #6
Opened 2021-07-29 15:13 UTC by antunes1611

tradução

2021-07-29 19:41 UTC, KitsuneModder requested changes

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/DesignationCategoryDef/DesignationCategories.xml
> +  <Hygiene.description>Coisas para higiene dos colonos.</Hygiene.description>
```suggestion
  <Hygiene.description>Construções para higiene dos colonos.</Hygiene.description>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/DubsBadHygiene.WashingJobDef/Jobs_Hygiene.xml
> +  </JobDef> -->
```suggestion

```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/DubsBadHygiene.WashingJobDef/Jobs_Hygiene.xml
> +  <takeShower.reportString>tomar banho com TargetA</takeShower.reportString>
```suggestion
  <takeShower.reportString>tomando banho com TargetA.</takeShower.reportString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/DubsBadHygiene.WashingJobDef/Jobs_Hygiene.xml
> +  <takeBath.reportString>tomando banho</takeBath.reportString>
```suggestion
  <takeBath.reportString>tomando banho.</takeBath.reportString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/HediffDefs/Hediffs.xml
> +            <Diarrhea.label>diarréia</Diarrhea.label>
```suggestion
            <Diarrhea.label>diarreia</Diarrhea.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/HediffDefs/Hediffs.xml
> +            <BionicBladder.labelNoun>a bexiga biônica</BionicBladder.labelNoun>
```suggestion
            <BionicBladder.labelNoun>uma bexiga biônica</BionicBladder.labelNoun>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/HediffDefs/Hediffs.xml
> +            <HygieneEnhancer.labelNoun>uma hygiene enhancer</HygieneEnhancer.labelNoun>
```suggestion
            <HygieneEnhancer.labelNoun>um melhorador de higiene</HygieneEnhancer.labelNoun>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/HediffDefs/Hediffs.xml
> +            <HygieneEnhancer.description>Um intensificador de higiene instalado.</HygieneEnhancer.description>
```suggestion
            <HygieneEnhancer.description>Um melhorador de higiene instalado.</HygieneEnhancer.description>
```
Seja consistente,

O google tradutor não é, corrija-o.

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <TriggerFireSprinkler.reportString>ativando TargetA</TriggerFireSprinkler.reportString>
```suggestion
        <TriggerFireSprinkler.reportString>ativando TargetA.</TriggerFireSprinkler.reportString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <emptySeptictank.reportString>esvaziar TargetA</emptySeptictank.reportString>
```suggestion
        <emptySeptictank.reportString>esvaziando TargetA.</emptySeptictank.reportString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <emptyLatrine.reportString>esvaziar TargetA</emptyLatrine.reportString>
```suggestion
        <emptyLatrine.reportString>esvaziando TargetA.</emptyLatrine.reportString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        </JobDef> -->
```suggestion

```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <PlaceFertilizer.reportString>fertilizando solo</PlaceFertilizer.reportString>
Ponto final ausente em boa parte.

Gerúndio ausente em algumas linhas.

Substituir ''merda'' por um termo mais agradável.

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <haveWildPoo.reportString>se cagando ao ar livre.</haveWildPoo.reportString>
Usar termo mais agradável.

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/KeyBindingCategoryDef/KeyBindingCategories.xml
> +        <Architect_Hygiene.label>guia de higiene</Architect_Hygiene.label>
```suggestion
        <Architect_Hygiene.label>Guia de Higiene</Architect_Hygiene.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/RecipeDef/Recipes.xml
> +  			<InstallHygieneEnhancer.jobString>Instalando intensificador de higiene.</InstallHygieneEnhancer.jobString>
```suggestion
  			<InstallHygieneEnhancer.jobString>Instalando melhorador de higiene.</InstallHygieneEnhancer.jobString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/RecipeDef/Recipes.xml
> +  			<Make_ChemfuelFromFecalSludge.jobString>Refinar o combustível químico da lama fecal</Make_ChemfuelFromFecalSludge.jobString>
```suggestion
  			<Make_ChemfuelFromFecalSludge.jobString>Refinando combustível químico de lama fecal</Make_ChemfuelFromFecalSludge.jobString>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <MultiSplitAirCon.description>Construir sistemas de ar condicionado multi-split com unidades externas canalizadas para unidades internas e freezers.</MultiSplitAirCon.description>
Traduzir mult-split

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <AdvancedShowers.label>chuveiros Elétricos</AdvancedShowers.label>
```suggestion
            <AdvancedShowers.label>chuveiros elétricos</AdvancedShowers.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <AdvancedToilets.label>vaso sanitário Avançado</AdvancedToilets.label>
```suggestion
            <AdvancedToilets.label>vaso sanitário avançado</AdvancedToilets.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <HygieneBionics.label>biônico higiênico</HygieneBionics.label>
?????????????

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TerrainDef/Terrains.xml
> +  </ThingDef> -->
```suggestion

```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TerrainDef/Terrains.xml
> +            <PoolWater.tools.0.label>agua</PoolWater.tools.0.label>
```suggestion
            <PoolWater.tools.0.label>água</PoolWater.tools.0.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TraitDef/Traits.xml
> +            <Hygienic.degreeDatas.0.description>[PAWN_nameDef] é obcecado por germes e se lavará com muito mais frequência do que o normal.</Hygienic.degreeDatas.0.description>
```suggestion
            <Hygienic.degreeDatas.0.description>[PAWN_nameDef] é obcecado(a) por germes e se lavará com muito mais frequência do que o normal.</Hygienic.degreeDatas.0.description>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TraitDef/Traits.xml
> +            <Hygienic.degreeDatas.1.description>[PAWN_nameDef] é muito higiênico e lava com mais frequência.</Hygienic.degreeDatas.1.description>
```suggestion
            <Hygienic.degreeDatas.1.description>[PAWN_nameDef] é muito higiênico(a) e lava as mãos com frequência.</Hygienic.degreeDatas.1.description>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TraitDef/Traits.xml
> +            <Hygienic.degreeDatas.2.description>[PAWN_nameDef] é muito anti-higiênico e lavará com menos frequência.</Hygienic.degreeDatas.2.description>
```suggestion
            <Hygienic.degreeDatas.2.description>[PAWN_nameDef] é muito anti-higiênico(a) e lavará suas mãos com menos frequência.</Hygienic.degreeDatas.2.description>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/TraitDef/Traits.xml
> +            <Hygienic.degreeDatas.3.description>[PAWN_nameDef] tem padrões de limpeza muito baixos e só lavará quando for absolutamente necessário.</Hygienic.degreeDatas.3.description>
```suggestion
            <Hygienic.degreeDatas.3.description>[PAWN_nameDef] tem padrões de limpeza muito baixos e só se lavará quando for absolutamente necessário.</Hygienic.degreeDatas.3.description>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <ClearBlockage.gerund>bloqueaando compensação</ClearBlockage.gerund>
????????????????????????

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <DBHAdministerFluids.gerund>dando bebida</DBHAdministerFluids.gerund>
Consistência

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <cleanBedpan.verb>limpa</cleanBedpan.verb>
```suggestion
            <cleanBedpan.verb>limpar</cleanBedpan.verb>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <RemoveSewage.label>Remover esgoto</RemoveSewage.label>
```suggestion
            <RemoveSewage.label>remover esgoto</RemoveSewage.label>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <LoadWashing.gerund>carregando roupas lavagem</LoadWashing.gerund>
```suggestion
            <LoadWashing.gerund>carregando roupas</LoadWashing.gerund>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <emptySepticTank.gerund>esvaziar</emptySepticTank.gerund>
????????

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <CleanFilthIndoors.verb>limpar/limpo</CleanFilthIndoors.verb>
```suggestion
            <CleanFilthIndoors.verb>limpar</CleanFilthIndoors.verb>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <DBHFalloutWarningEx>Após 2 dias de precipitação tóxica, o acúmulo contaminará todos os tanques de armazenamento de água conectados aos poços de água. \n\nPrepare criando uma reserva de água e usan
```suggestion
  <DBHFalloutWarningEx>Após 2 dias de precipitação tóxica, o acúmulo contaminará todos os tanques de armazenamento de água conectados aos poços de água.\n\nPrepare criando uma reserva de água e usando uma válvula para desconectar os poços para proteger a água da contaminação antes que seja tarde demais.\n\nVocê também pode usar um poço profundo para acessar água não contaminada ou instalar um sistema de tratamento de água que eliminará toda a contaminação das reservas de água.</DBHFalloutWarningEx>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <ContaminationAlertDesc>Um poço ficou poluído. \n\nFontes de contaminação: \n{0} \n\nMova o poço, remova as fontes de contaminação ou, se estiver usando poços encanados, adicione um sistema de trat
```suggestion
  <ContaminationAlertDesc>Um poço ficou poluído.\n\nFontes de contaminação:\n{0}\n\nMova o poço, remova as fontes de contaminação ou, se estiver usando poços encanados, adicione um sistema de tratamento de água, que também limpará os contaminados a água aumenta com o tempo.</ContaminationAlertDesc>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <dbh.ModRemoveDesc>Passos: \n\n1: Salve seu jogo imediatamente após pressionar confirmar \n2: Saia do menu principal, desabilite o mod e reinicie o jogo \n3: carregue seu jogo salvo, ignore quaisqu
```suggestion
  <dbh.ModRemoveDesc>Passos:\n\n1: Salve seu jogo imediatamente após pressionar confirmar\n2: Saia do menu principal, desabilite o mod e reinicie o jogo\n3: carregue seu jogo salvo, ignore quaisquer exceções e salve-o novamente\nCarregue o jogo salvo mais uma vez e não deve haver nenhuma exceção relacionada à falta de defs ou aulas de higiene inadequada!</dbh.ModRemoveDesc>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <fixtureQualityTip>Habilite ''quality and art comps'' para acessórios como banheiros</fixtureQualityTip>
Traduzir

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <DBHLiteModeTip>Mude o modo para um modo simplificado que remove canos, gerenciamento de água e esgoto e quaisquer edifícios e trabalhos não diretamente relacionados à higiene e sede. \n\nIsso impe
```suggestion
  <DBHLiteModeTip>Mude o modo para um modo simplificado que remove canos, gerenciamento de água e esgoto e quaisquer edifícios e trabalhos não diretamente relacionados à higiene e sede.\n\nIsso impedirá que muitos defs sejam carregados e exigirá uma reinicialização.\n\nSe você estiver tentando carregar um save com edifícios de higiene existentes, você pode precisar salvar e recarregar após ativar</DBHLiteModeTip>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <SurvivalModeTip>Limita a geração padrão da rede de águas rasas a manchas muito pequenas. Os recursos do terreno não geram mais água e o raio ao redor da água da superfície é reduzido. \n\nNão é ne
```suggestion
  <SurvivalModeTip>Limita a geração padrão da rede de águas rasas a manchas muito pequenas. Os recursos do terreno não geram mais água e o raio ao redor da água da superfície é reduzido.\n\nNão é necessário um novo jogo; funciona com salvamentos existentes.</SurvivalModeTip>
```

2021-07-29 19:41 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <ThirstRequiresRestart>É necessário reiniciar para adicionar e remover itens relacionados à sede. \n\nReiniciar agora?</ThirstRequiresRestart>
```suggestion
  <ThirstRequiresRestart>É necessário reiniciar para adicionar e remover itens relacionados à sede.\n\nReiniciar agora?</ThirstRequiresRestart>
```

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <emptySepticTank.gerund>esvaziar</emptySepticTank.gerund>
?????

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <DBHAdministerFluids.gerund>dando bebida</DBHAdministerFluids.gerund>
????

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/WorkGiverDef/WorkGivers.xml
> +            <ClearBlockage.gerund>bloqueaando compensação</ClearBlockage.gerund>
???????

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <MultiSplitAirCon.description>Construir sistemas de ar condicionado multi-split com unidades externas canalizadas para unidades internas e freezers.</MultiSplitAirCon.description>
sugestão

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <HygieneBionics.label>biônico higiênico</HygieneBionics.label>
????

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <haveWildPoo.reportString>se cagando ao ar livre.</haveWildPoo.reportString>
sugestão

2021-07-29 22:46 UTC, antunes1611 commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <PlaceFertilizer.reportString>fertilizando solo</PlaceFertilizer.reportString>
sugestão

2021-07-29 22:48 UTC, antunes1611 commented on Languages/PortugueseBrazilian/Keyed/Keys.xml
> +  <fixtureQualityTip>Habilite ''quality and art comps'' para acessórios como banheiros</fixtureQualityTip>
nome de mod

2021-07-30 16:14 UTC, KitsuneModder requested changes

2021-07-30 16:14 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/JobDef/Jobs.xml
> +        <UseToilet.reportString>TargetA esta se cagando.</UseToilet.reportString>
Termo.

2021-07-30 16:14 UTC, KitsuneModder commented on Languages/PortugueseBrazilian/DefInjected/ResearchProjectDef/ResearchProjects.xml
> +            <HygieneBionics.label>biônico higiênico</HygieneBionics.label>
O que é um biônico higiênio^?????

2021-08-02 17:10 UTC, merged